### ISSUE TITLE
Typescript declaration

### ISSUE THREAD

**Issue by RomainClaret** [flickz/helloworldjs#1]
**helloworldjs.d.ts**

```
declare module "helloworldjs/helloworldjs" {
  function greetCall(language: string): void
  function greetReturn(language: string): string
}
```

**Comment by flickz** [comment]
Hi @Rocla, The project is in JavaScript not Typescript or maybe I don't clearly understand your point with the code above. Might be helpful to explain a little further. Thanks

**Comment by RomainClaret** [comment]
@flickz Yep, your project is in javascript, that's why I made a [declaration file](https://basarat.gitbooks.io/typescript/docs/types/ambient/d.ts.html) for it, to be used with typescript.

It's called issue, but it's really not. I was trying some stuff, I installed your module, and made a quick declaration file (because I use Typescript). And instead of just deleting my project like nothing happended, and since I was too lazy to make a pull request, I shared the declaration file with you, just in case, you, or someone else, would be interested.
